<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <title>{{ $payslip->payslip_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #111827; font-size: 12px; margin: 28px; }
        .header { border-bottom: 2px solid #0f172a; padding-bottom: 14px; margin-bottom: 20px; }
        .title { font-size: 22px; font-weight: bold; margin: 0; }
        .subtitle { color: #475569; margin-top: 6px; }
        .grid { width: 100%; margin-bottom: 18px; }
        .grid td { width: 50%; vertical-align: top; padding: 6px 0; }
        .card { border: 1px solid #d4d4d8; border-radius: 12px; padding: 14px; margin-bottom: 18px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 10px 8px; border-bottom: 1px solid #e5e7eb; text-align: left; }
        th { font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: #64748b; }
        .text-right { text-align: right; }
        .totals td { border: none; padding: 4px 0; }
        .footer { margin-top: 22px; color: #64748b; font-size: 11px; }
    </style>
</head>
<body>
    <div class="header">
        <p class="title">{{ __('HARIS payslip') }}</p>
        <p class="subtitle">{{ $payslip->payslip_number }} | {{ $period->period_name }}</p>
    </div>

    <table class="grid">
        <tr>
            <td>
                <strong>{{ __('Employee') }}</strong><br>
                {{ $employee->full_name }}<br>
                {{ $employee->employee_number }}<br>
                {{ $employee->organization?->name ?? __('No organization') }}
            </td>
            <td>
                <strong>{{ __('Payroll information') }}</strong><br>
                {{ __('Group') }}: {{ $period->payrollGroup?->name ?? '-' }}<br>
                {{ __('Pay date') }}: {{ optional($payslip->issue_date)->format('d M Y') ?? '-' }}<br>
                {{ __('Status') }}: {{ __(ucfirst($run->calculation_status->value)) }}
            </td>
        </tr>
    </table>

    <div class="card">
        <table>
            <thead>
                <tr>
                    <th>{{ __('Component') }}</th>
                    <th>{{ __('Type') }}</th>
                    <th class="text-right">{{ __('Amount') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($run->items->sortBy('sort_order') as $item)
                    <tr>
                        <td>{{ $item->component_name }}</td>
                        <td>{{ strtoupper($item->component_type) }}</td>
                        <td class="text-right">{{ number_format((float) $item->amount, 0, ',', '.') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="card">
        <table class="totals">
            <tr>
                <td>{{ __('Gross salary') }}</td>
                <td class="text-right">{{ number_format((float) $run->gross_salary, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <td>{{ __('Total deduction') }}</td>
                <td class="text-right">{{ number_format((float) $run->total_deduction, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <td>{{ __('Total PPh21') }}</td>
                <td class="text-right">{{ number_format((float) $run->total_pph21, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <td><strong>{{ __('Take home pay') }}</strong></td>
                <td class="text-right"><strong>{{ number_format((float) $run->take_home_pay, 0, ',', '.') }}</strong></td>
            </tr>
        </table>
    </div>

    <div class="footer">
        {{ __('Generated by HARIS on :date.', ['date' => now()->format('d M Y H:i')]) }}
    </div>
</body>
</html>
